[package]
name = "builtins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slvm = { path = "../vm" }
compile_state = { path = "../compile_state" }
unicode-segmentation = "1.10.1"
bridge_types = { workspace = true }
bridge_macros = { path = "../bridge_macros" }
