[package]
name = "compiler_test_utils"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sl-compiler = { workspace = true }
slvm = { workspace = true }
compile_state = { workspace = true }
